Workflows: Fix inefficient json validation

diff --git a/.github/workflows/get-addon-catalog.yaml b/.github/workflows/get-addon-catalog.yaml
--- a/.github/workflows/get-addon-catalog.yaml
+++ b/.github/workflows/get-addon-catalog.yaml
@@ -99,10 +99,7 @@ jobs:
 
           echo "Validating $FILE..."
 
-          if ! python3 -m json.tool "$FILE"; then
-            echo "Error: $FILE is not valid JSON."
-            exit 1
-          fi
+          jq empty "$FILE" || (echo "Error: $FILE is not valid JSON." && exit 1)
 
       - name: Cleanup Addon JSON
         if: steps.fetch_zip.outputs.changed == 'true'
